# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JudgingSystem', '0002_judge_project_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='session_ptr',
        ),
        migrations.AlterField(
            model_name='rating',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
