# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JudgingSystem', '0004_rating_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='standardized_originality',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='standardized_polish',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='standardized_technical_difficulty',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='standardized_usefulness',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
