# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JudgingSystem', '0005_auto_20170225_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='mean_standardized_score',
        ),
    ]
